dofile("data/scripts/lib/mod_settings.lua")

local mod_id = "Custom_Start"
mod_settings_version = 1

local spell_images_path = "mods/Custom Start/data/items_gfx/Spell Images/"

-- Define mod settings
mod_settings = {
    {
        category_id = "Custom_Start_settings",
        ui_name = "Starting Stats",
        settings = {
            {
                id = "starting_health",
                ui_name = "Starting Health",
                ui_description = "Set the amount of health you start with.",
                value_default = "100",
                text_max_length = 5,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
                setting_type = MOD_SETTING_TYPE_TEXT,
            },
            {
                id = "starting_gold",
                ui_name = "Starting Gold",
                ui_description = "Set the amount of gold you start with.",
                value_default = "0",
                text_max_length = 5,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
                setting_type = MOD_SETTING_TYPE_TEXT,
            },
        },
    },
    {
        category_id = "Custom_Start_primary",
        ui_name = "Primary Wand",
        settings = {
            {
                id = "primary_spell",
                ui_name = "Primary Spell",
                ui_description = "What spell would you like to start with?",
                value_default = "1",
                values = {
                    {"1", "Acid Ball"},
                    {"2", "Black Hole"},
                    {"3", "Black Hole with Death Trigger"},
                    {"4", "Bomb"},
                    {"5", "Bomb Cart"},
                    {"6", "Bubble Spark"},
                    {"7", "Bubble Spark With Trigger"},
                    {"8", "Burst Of Air"},
                    {"9", "Chain Bolt"},
                    {"10", "Chainsaw"},
                    {"11", "Cursed Sphere"},
                    {"12", "Deadly Heal"},
                    {"13", "Death Cross"},
                    {"14", "Giga Death Cross"},
                    {"15", "Plasma Beam Cross"},
                    {"16", "Digging Blast"},
                    {"17", "Digging Bolt"},
                    {"18", "Dormant Crystal"},
                    {"19", "Dormant Crystal With Trigger"},
                    {"20", "Dropper Bolt"},
                    {"21", "Dynamite"},
                    {"22", "Earthquake"},
                    {"23", "Eldritch Portal"},
                    {"24", "Energy Orb"},
                    {"25", "Energy Orb With A Trigger"},
                    {"26", "Energy Orb With A Timer"},
                    {"27", "Expanding Sphere"},
                    {"28", "Fireball"},
                    {"29", "Firebolt"},
                    {"30", "Firebolt With Trigger"},
                    {"31", "Large Firebolt"},
                    {"32", "Giant Firebolt"},
                    {"33", "Odd Firebolt"},
                    {"34", "Firebomb"},
                    {"35", "Fireworks!"},
                    {"36", "Flamethrower"},
                    {"37", "Glitter Bomb"},
                    {"38", "Glowing Lance"},
                    {"39", "Glue Ball"},
                    {"40", "Healing Bolt"},
                    {"41", "Holy Lance"},
                    {"42", "Holy Bomb"},
                    {"43", "Giga Holy Bomb"},
                    {"44", "Hookbolt"},
                    {"45", "Iceball"},
                    {"46", "Concentrated Light"},
                    {"47", "Lightning Bolt"},
                    {"48", "Thunder Charge"},
                    {"49", "Ball Lightning"},
                    {"50", "Luminous Drill"},
                    {"51", "Luminous Drill With Timer"},
                    {"52", "Magic Arrow"},
                    {"53", "Magic Arrow With Trigger"},
                    {"54", "Magic Arrow With Timer"},
                    {"55", "Magic Bolt"},
                    {"56", "Magic Bolt With Trigger"},
                    {"57", "Magic Bolt With Timer"},
                    {"58", "Magic Guard"},
                    {"59", "Big Magic Guard"},
                    {"60", "Magic Missile"},
                    {"61", "Large Magic Missile"},
                    {"62", "Giant Magic Missile"},
                    {"63", "Meteor"},
                    {"64", "Blood Mist"},
                    {"65", "Mist Of Spirits"},
                    {"66", "Slime Mist"},
                    {"67", "Toxic Mist"},
                    {"68", "Freezing Gaze"},
                    {"69", "Triplicate Bolt"},
                    {"70", "Intense Concentrated Light"},
                    {"71", "Flock Of Ducks"},
                    {"72", "Infestation"},
                    {"73", "Nuke"},
                    {"74", "Giga Nuke"},
                    {"75", "Path Of Dark Flame"},
                    {"76", "Pinpoint Of Light"},
                    {"77", "Plasma Beam"},
                    {"78", "Plasma Cutter"},
                    {"79", "Pollen"},
                    {"80", "Prickly Spore Pod"},
                    {"81", "Propane Tank"},
                    {"82", "Random Projectile Spell"},
                    {"83", "Rock"},
                    {"84", "Disc Projectile"},
                    {"85", "Giga Disc Projectile"},
                    {"86", "Summon Omega Sawblade"},
                    {"87", "Slimeball"},
                    {"88", "Spark Bolt"},
                    {"89", "Spark Bolt With Trigger"},
                    {"90", "Spark Bolt With Double Trigger"},
                    {"91", "Spark Bolt With Timer"},
                    {"92", "Bouncing Burst"},
                    {"93", "Energy Sphere"},
                    {"94", "Arrow"},
                    {"95", "Energy Sphere With Timer"},
                    {"96", "Spiral Shot"},
                    {"97", "Spitter Bolt"},
                    {"98", "Spitter Bolt With Timer"},
                    {"99", "Large Spitter Bolt"},
                    {"100", "Large Spitter Bolt With Timer"},
                    {"101", "Giant Spitter Bolt"},
                    {"102", "Giant Spitter Bolt With Timer"},
                    {"103", "Summon Deercoy"},
                    {"104", "Summon Egg"},
                    {"105", "Summon Explosive Box"},
                    {"106", "Summon Large Explosive Box"},
                    {"107", "Summon Fish"},
                    {"108", "Summon Hollow Egg"},
                    {"109", "Summon Missile"},
                    {"110", "Summon Rock Spirit"},
                    {"111", "Summon Tentacle"},
                    {"112", "Summon Tentacle With Timer"},
                    {"113", "Swapper"},
                    {"114", "Homebringer Teleport Bolt"},
                    {"115", "Teleport Bolt"},
                    {"116", "Return"},
                    {"117", "Small Teleport Bolt"},
                    {"118", "Unstable Crystal"},
                    {"119", "Unstable Crystal With Trigger"},
                    {"120", "White Hole"},
                    {"121", "Worm Launcher"},
                    {"122", "Horizontal Barrier"},
                    {"123", "Vertical Barrier"},
                    {"124", "Square Barrier"},
                    {"125", "Circle of Unstable Metamorphosis"},
                    {"126", "Circle of Shielding"},
                    {"127", "Circle of Transmogrification"},
                    {"128", "Circle of Buoyancy"},
                    {"129", "Circle of Fervour"},
                    {"130", "Circle of Displacement"},
                    {"131", "Circle of Stillness"},
                    {"132", "Circle of Thunder"},
                    {"133", "Circle of Vigour"},
                    {"134", "Rain Cloud"},
                    {"135", "Oil Cloud"},
                    {"136", "Blood Cloud"},
                    {"137", "Acid Cloud"},
                    {"138", "Thundercloud"},
                    {"139", "Destruction"},
                    {"140", "Explosive Detonator"},
                    {"141", "Glittering Field"},
                    {"142", "Matosade"},
                    {"143", "Meteorisade"},
                    {"144", "Summon Fly Swarm"},
                    {"145", "Summon Firebug Swarm"},
                    {"146", "Summon Wasp Swarm"},
                    {"147", "Delayed Spellcast"},
                    {"148", "Muodonmuutos"},
                    {"149", "Projectile Transmutation Field"},
                    {"150", "Projectile Thunder Field"},
                    {"151", "Projectile Gravity Field"},
                    {"152", "Random Static Projectile Spell"},
                    {"153", "Omega Black Hole"},
                    {"154", "Giga White Hole"},
                    {"155", "Giga Black Hole"},
                    {"156", "Explosion"},
                    {"157", "Explosion of Brimstone"},
                    {"158", "Explosion of Poison"},
                    {"159", "Explosion of Spirits"},
                    {"160", "Explosion of Thunder"},
                    {"161", "Magical Explosion"},
                    {"162", "Omega White Hole"},
                    {"163", "Summon Friendly Fly"},
                    {"164", "Powder Vacuum Field"},
                    {"165", "Vacuum Field"},
                    {"166", "Liquid Vacuum Field"}
                },
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "primary_cast_delay",
                ui_name = "Primary Cast Delay",
                ui_description = "Set the cast delay for the primary wand.",
                value_default = 12,
                value_min = 1,
                value_max = 100,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "primary_mana_recharge",
                ui_name = "Primary Mana Recharge Speed",
                ui_description = "Set the mana recharge speed for the primary wand.",
                value_default = 32.5,
                value_min = 10,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "primary_max_mana",
                ui_name = "Primary Max Mana",
                ui_description = "Set the max mana for the primary wand.",
                value_default = 105,
                value_min = 1,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
        },
    },
    {
        category_id = "Custom_Start_secondary",
        ui_name = "Secondary Wand",
        settings = {
            {
                id = "secondary_spell",
                ui_name = "Secondary Spell",
                ui_description = "What spell would you like to start with?",
                value_default = "1",
                values = {
                    {"1", "TNT"},
                    {"2", "Bomb"},
                    {"3", "Bomb Cart"},
                    {"4", "Propane Tank"},
                    {"5", "Summon Explosive Box"},
                    {"6", "Summon Large Explosive Box"},
                    {"7", "Holy Bomb"},
                    {"8", "Nuke"},
                    {"9", "Firebomb"},
                    {"10", "Firebolt"},
                    {"11", "Odd Firebolt"},
                    {"12", "Firebolt With Trigger"},
                    {"13", "Dropper Bolt"},
                    {"14", "Large Firebolt"},
                    {"15", "Giant Firebolt"},
                    {"16", "Unstable Crystal"},
                    {"17", "Unstable Crystal With Trigger"},
                    {"18", "Dormant Crystal"},
                    {"19", "Dormant Crystal With Trigger"},
                    {"20", "Magic Missile"},
                    {"21", "Large Magic Missile"},
                    {"22", "Giant Magic Missile"},
                    {"23", "Summon Missile"}

                },
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "secondary_cast_delay",
                ui_name = "Secondary Cast Delay",
                ui_description = "Set the cast delay for the secondary wand.",
                value_default = 12,
                value_min = 1,
                value_max = 100,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "secondary_mana_recharge",
                ui_name = "Secondary Mana Recharge Speed",
                ui_description = "Set the mana recharge speed for the secondary wand.",
                value_default = 32.5,
                value_min = 10,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "secondary_max_mana",
                ui_name = "Secondary Max Mana",
                ui_description = "Set the max mana for the secondary wand.",
                value_default = 105,
                value_min = 1,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
        },
    },
    {
        category_id = "Custom_Start_tertiary",
        ui_name = "Tertiary Wand",
        settings = {
            {
                id = "enable_tertiary_wand",
                ui_name = "Enable Tertiary Wand",
                ui_description = "Toggle to enable or disable the tertiary wand.",
                value_default = true,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
                setting_type = MOD_SETTING_TYPE_BOOL,
            },
            {
                id = "tertiary_spell",
                ui_name = "Tertiary Spell",
                ui_description = "What spell would you like to start with?",
                value_default = "1",
                values = {
                    {"1", "Acid Ball"},
                    {"2", "Black Hole"},
                    {"3", "Black Hole with Death Trigger"},
                    {"4", "Bomb"},
                    {"5", "Bomb Cart"},
                    {"6", "Bubble Spark"},
                    {"7", "Bubble Spark With Trigger"},
                    {"8", "Burst Of Air"},
                    {"9", "Chain Bolt"},
                    {"10", "Chainsaw"},
                    {"11", "Cursed Sphere"},
                    {"12", "Deadly Heal"},
                    {"13", "Death Cross"},
                    {"14", "Giga Death Cross"},
                    {"15", "Plasma Beam Cross"},
                    {"16", "Digging Blast"},
                    {"17", "Digging Bolt"},
                    {"18", "Dormant Crystal"},
                    {"19", "Dormant Crystal With Trigger"},
                    {"20", "Dropper Bolt"},
                    {"21", "Dynamite"},
                    {"22", "Earthquake"},
                    {"23", "Eldritch Portal"},
                    {"24", "Energy Orb"},
                    {"25", "Energy Orb With A Trigger"},
                    {"26", "Energy Orb With A Timer"},
                    {"27", "Expanding Sphere"},
                    {"28", "Fireball"},
                    {"29", "Firebolt"},
                    {"30", "Firebolt With Trigger"},
                    {"31", "Large Firebolt"},
                    {"32", "Giant Firebolt"},
                    {"33", "Odd Firebolt"},
                    {"34", "Firebomb"},
                    {"35", "Fireworks!"},
                    {"36", "Flamethrower"},
                    {"37", "Glitter Bomb"},
                    {"38", "Glowing Lance"},
                    {"39", "Glue Ball"},
                    {"40", "Healing Bolt"},
                    {"41", "Holy Lance"},
                    {"42", "Holy Bomb"},
                    {"43", "Giga Holy Bomb"},
                    {"44", "Hookbolt"},
                    {"45", "Iceball"},
                    {"46", "Concentrated Light"},
                    {"47", "Lightning Bolt"},
                    {"48", "Thunder Charge"},
                    {"49", "Ball Lightning"},
                    {"50", "Luminous Drill"},
                    {"51", "Luminous Drill With Timer"},
                    {"52", "Magic Arrow"},
                    {"53", "Magic Arrow With Trigger"},
                    {"54", "Magic Arrow With Timer"},
                    {"55", "Magic Bolt"},
                    {"56", "Magic Bolt With Trigger"},
                    {"57", "Magic Bolt With Timer"},
                    {"58", "Magic Guard"},
                    {"59", "Big Magic Guard"},
                    {"60", "Magic Missile"},
                    {"61", "Large Magic Missile"},
                    {"62", "Giant Magic Missile"},
                    {"63", "Meteor"},
                    {"64", "Blood Mist"},
                    {"65", "Mist Of Spirits"},
                    {"66", "Slime Mist"},
                    {"67", "Toxic Mist"},
                    {"68", "Freezing Gaze"},
                    {"69", "Triplicate Bolt"},
                    {"70", "Intense Concentrated Light"},
                    {"71", "Flock Of Ducks"},
                    {"72", "Infestation"},
                    {"73", "Nuke"},
                    {"74", "Giga Nuke"},
                    {"75", "Path Of Dark Flame"},
                    {"76", "Pinpoint Of Light"},
                    {"77", "Plasma Beam"},
                    {"78", "Plasma Cutter"},
                    {"79", "Pollen"},
                    {"80", "Prickly Spore Pod"},
                    {"81", "Propane Tank"},
                    {"82", "Random Projectile Spell"},
                    {"83", "Rock"},
                    {"84", "Disc Projectile"},
                    {"85", "Giga Disc Projectile"},
                    {"86", "Summon Omega Sawblade"},
                    {"87", "Slimeball"},
                    {"88", "Spark Bolt"},
                    {"89", "Spark Bolt With Trigger"},
                    {"90", "Spark Bolt With Double Trigger"},
                    {"91", "Spark Bolt With Timer"},
                    {"92", "Bouncing Burst"},
                    {"93", "Energy Sphere"},
                    {"94", "Arrow"},
                    {"95", "Energy Sphere With Timer"},
                    {"96", "Spiral Shot"},
                    {"97", "Spitter Bolt"},
                    {"98", "Spitter Bolt With Timer"},
                    {"99", "Large Spitter Bolt"},
                    {"100", "Large Spitter Bolt With Timer"},
                    {"101", "Giant Spitter Bolt"},
                    {"102", "Giant Spitter Bolt With Timer"},
                    {"103", "Summon Deercoy"},
                    {"104", "Summon Egg"},
                    {"105", "Summon Explosive Box"},
                    {"106", "Summon Large Explosive Box"},
                    {"107", "Summon Fish"},
                    {"108", "Summon Hollow Egg"},
                    {"109", "Summon Missile"},
                    {"110", "Summon Rock Spirit"},
                    {"111", "Summon Tentacle"},
                    {"112", "Summon Tentacle With Timer"},
                    {"113", "Swapper"},
                    {"114", "Homebringer Teleport Bolt"},
                    {"115", "Teleport Bolt"},
                    {"116", "Return"},
                    {"117", "Small Teleport Bolt"},
                    {"118", "Unstable Crystal"},
                    {"119", "Unstable Crystal With Trigger"},
                    {"120", "White Hole"},
                    {"121", "Worm Launcher"},
                    {"122", "Horizontal Barrier"},
                    {"123", "Vertical Barrier"},
                    {"124", "Square Barrier"},
                    {"125", "Circle of Unstable Metamorphosis"},
                    {"126", "Circle of Shielding"},
                    {"127", "Circle of Transmogrification"},
                    {"128", "Circle of Buoyancy"},
                    {"129", "Circle of Fervour"},
                    {"130", "Circle of Displacement"},
                    {"131", "Circle of Stillness"},
                    {"132", "Circle of Thunder"},
                    {"133", "Circle of Vigour"},
                    {"134", "Rain Cloud"},
                    {"135", "Oil Cloud"},
                    {"136", "Blood Cloud"},
                    {"137", "Acid Cloud"},
                    {"138", "Thundercloud"},
                    {"139", "Destruction"},
                    {"140", "Explosive Detonator"},
                    {"141", "Glittering Field"},
                    {"142", "Matosade"},
                    {"143", "Meteorisade"},
                    {"144", "Summon Fly Swarm"},
                    {"145", "Summon Firebug Swarm"},
                    {"146", "Summon Wasp Swarm"},
                    {"147", "Delayed Spellcast"},
                    {"148", "Muodonmuutos"},
                    {"149", "Projectile Transmutation Field"},
                    {"150", "Projectile Thunder Field"},
                    {"151", "Projectile Gravity Field"},
                    {"152", "Random Static Projectile Spell"},
                    {"153", "Omega Black Hole"},
                    {"154", "Giga White Hole"},
                    {"155", "Giga Black Hole"},
                    {"156", "Explosion"},
                    {"157", "Explosion of Brimstone"},
                    {"158", "Explosion of Poison"},
                    {"159", "Explosion of Spirits"},
                    {"160", "Explosion of Thunder"},
                    {"161", "Magical Explosion"},
                    {"162", "Omega White Hole"},
                    {"163", "Summon Friendly Fly"},
                    {"164", "Powder Vacuum Field"},
                    {"165", "Vacuum Field"},
                    {"166", "Liquid Vacuum Field"}
                },
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "tertiary_cast_delay",
                ui_name = "Tertiary Cast Delay",
                ui_description = "Set the cast delay for the tertiary wand.",
                value_default = 12,
                value_min = 1,
                value_max = 100,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "tertiary_mana_recharge",
                ui_name = "Tertiary Mana Recharge Speed",
                ui_description = "Set the mana recharge speed for the tertiary wand.",
                value_default = 32.5,
                value_min = 10,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "tertiary_max_mana",
                ui_name = "Tertiary Max Mana",
                ui_description = "Set the max mana for the tertiary wand.",
                value_default = 105,
                value_min = 1,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
        },
    },
    {
        category_id = "Custom_Start_quaternary",
        ui_name = "Quaternary Wand",
        settings = {
            {
                id = "enable_quaternary_wand",
                ui_name = "Enable Quaternary Wand",
                ui_description = "Toggle to enable or disable the quaternary wand.",
                value_default = true,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
                setting_type = MOD_SETTING_TYPE_BOOL,
            },
            {
                id = "quaternary_spell",
                ui_name = "Quaternary Spell",
                ui_description = "What spell would you like to start with?",
                value_default = "1",
                values = {
                    {"1", "Acid Ball"},
                    {"2", "Black Hole"},
                    {"3", "Black Hole with Death Trigger"},
                    {"4", "Bomb"},
                    {"5", "Bomb Cart"},
                    {"6", "Bubble Spark"},
                    {"7", "Bubble Spark With Trigger"},
                    {"8", "Burst Of Air"},
                    {"9", "Chain Bolt"},
                    {"10", "Chainsaw"},
                    {"11", "Cursed Sphere"},
                    {"12", "Deadly Heal"},
                    {"13", "Death Cross"},
                    {"14", "Giga Death Cross"},
                    {"15", "Plasma Beam Cross"},
                    {"16", "Digging Blast"},
                    {"17", "Digging Bolt"},
                    {"18", "Dormant Crystal"},
                    {"19", "Dormant Crystal With Trigger"},
                    {"20", "Dropper Bolt"},
                    {"21", "Dynamite"},
                    {"22", "Earthquake"},
                    {"23", "Eldritch Portal"},
                    {"24", "Energy Orb"},
                    {"25", "Energy Orb With A Trigger"},
                    {"26", "Energy Orb With A Timer"},
                    {"27", "Expanding Sphere"},
                    {"28", "Fireball"},
                    {"29", "Firebolt"},
                    {"30", "Firebolt With Trigger"},
                    {"31", "Large Firebolt"},
                    {"32", "Giant Firebolt"},
                    {"33", "Odd Firebolt"},
                    {"34", "Firebomb"},
                    {"35", "Fireworks!"},
                    {"36", "Flamethrower"},
                    {"37", "Glitter Bomb"},
                    {"38", "Glowing Lance"},
                    {"39", "Glue Ball"},
                    {"40", "Healing Bolt"},
                    {"41", "Holy Lance"},
                    {"42", "Holy Bomb"},
                    {"43", "Giga Holy Bomb"},
                    {"44", "Hookbolt"},
                    {"45", "Iceball"},
                    {"46", "Concentrated Light"},
                    {"47", "Lightning Bolt"},
                    {"48", "Thunder Charge"},
                    {"49", "Ball Lightning"},
                    {"50", "Luminous Drill"},
                    {"51", "Luminous Drill With Timer"},
                    {"52", "Magic Arrow"},
                    {"53", "Magic Arrow With Trigger"},
                    {"54", "Magic Arrow With Timer"},
                    {"55", "Magic Bolt"},
                    {"56", "Magic Bolt With Trigger"},
                    {"57", "Magic Bolt With Timer"},
                    {"58", "Magic Guard"},
                    {"59", "Big Magic Guard"},
                    {"60", "Magic Missile"},
                    {"61", "Large Magic Missile"},
                    {"62", "Giant Magic Missile"},
                    {"63", "Meteor"},
                    {"64", "Blood Mist"},
                    {"65", "Mist Of Spirits"},
                    {"66", "Slime Mist"},
                    {"67", "Toxic Mist"},
                    {"68", "Freezing Gaze"},
                    {"69", "Triplicate Bolt"},
                    {"70", "Intense Concentrated Light"},
                    {"71", "Flock Of Ducks"},
                    {"72", "Infestation"},
                    {"73", "Nuke"},
                    {"74", "Giga Nuke"},
                    {"75", "Path Of Dark Flame"},
                    {"76", "Pinpoint Of Light"},
                    {"77", "Plasma Beam"},
                    {"78", "Plasma Cutter"},
                    {"79", "Pollen"},
                    {"80", "Prickly Spore Pod"},
                    {"81", "Propane Tank"},
                    {"82", "Random Projectile Spell"},
                    {"83", "Rock"},
                    {"84", "Disc Projectile"},
                    {"85", "Giga Disc Projectile"},
                    {"86", "Summon Omega Sawblade"},
                    {"87", "Slimeball"},
                    {"88", "Spark Bolt"},
                    {"89", "Spark Bolt With Trigger"},
                    {"90", "Spark Bolt With Double Trigger"},
                    {"91", "Spark Bolt With Timer"},
                    {"92", "Bouncing Burst"},
                    {"93", "Energy Sphere"},
                    {"94", "Arrow"},
                    {"95", "Energy Sphere With Timer"},
                    {"96", "Spiral Shot"},
                    {"97", "Spitter Bolt"},
                    {"98", "Spitter Bolt With Timer"},
                    {"99", "Large Spitter Bolt"},
                    {"100", "Large Spitter Bolt With Timer"},
                    {"101", "Giant Spitter Bolt"},
                    {"102", "Giant Spitter Bolt With Timer"},
                    {"103", "Summon Deercoy"},
                    {"104", "Summon Egg"},
                    {"105", "Summon Explosive Box"},
                    {"106", "Summon Large Explosive Box"},
                    {"107", "Summon Fish"},
                    {"108", "Summon Hollow Egg"},
                    {"109", "Summon Missile"},
                    {"110", "Summon Rock Spirit"},
                    {"111", "Summon Tentacle"},
                    {"112", "Summon Tentacle With Timer"},
                    {"113", "Swapper"},
                    {"114", "Homebringer Teleport Bolt"},
                    {"115", "Teleport Bolt"},
                    {"116", "Return"},
                    {"117", "Small Teleport Bolt"},
                    {"118", "Unstable Crystal"},
                    {"119", "Unstable Crystal With Trigger"},
                    {"120", "White Hole"},
                    {"121", "Worm Launcher"},
                    {"122", "Horizontal Barrier"},
                    {"123", "Vertical Barrier"},
                    {"124", "Square Barrier"},
                    {"125", "Circle of Unstable Metamorphosis"},
                    {"126", "Circle of Shielding"},
                    {"127", "Circle of Transmogrification"},
                    {"128", "Circle of Buoyancy"},
                    {"129", "Circle of Fervour"},
                    {"130", "Circle of Displacement"},
                    {"131", "Circle of Stillness"},
                    {"132", "Circle of Thunder"},
                    {"133", "Circle of Vigour"},
                    {"134", "Rain Cloud"},
                    {"135", "Oil Cloud"},
                    {"136", "Blood Cloud"},
                    {"137", "Acid Cloud"},
                    {"138", "Thundercloud"},
                    {"139", "Destruction"},
                    {"140", "Explosive Detonator"},
                    {"141", "Glittering Field"},
                    {"142", "Matosade"},
                    {"143", "Meteorisade"},
                    {"144", "Summon Fly Swarm"},
                    {"145", "Summon Firebug Swarm"},
                    {"146", "Summon Wasp Swarm"},
                    {"147", "Delayed Spellcast"},
                    {"148", "Muodonmuutos"},
                    {"149", "Projectile Transmutation Field"},
                    {"150", "Projectile Thunder Field"},
                    {"151", "Projectile Gravity Field"},
                    {"152", "Random Static Projectile Spell"},
                    {"153", "Omega Black Hole"},
                    {"154", "Giga White Hole"},
                    {"155", "Giga Black Hole"},
                    {"156", "Explosion"},
                    {"157", "Explosion of Brimstone"},
                    {"158", "Explosion of Poison"},
                    {"159", "Explosion of Spirits"},
                    {"160", "Explosion of Thunder"},
                    {"161", "Magical Explosion"},
                    {"162", "Omega White Hole"},
                    {"163", "Summon Friendly Fly"},
                    {"164", "Powder Vacuum Field"},
                    {"165", "Vacuum Field"},
                    {"166", "Liquid Vacuum Field"}
                },
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "quaternary_cast_delay",
                ui_name = "Quaternary Cast Delay",
                ui_description = "Set the cast delay for the quaternary wand.",
                value_default = 12,
                value_min = 1,
                value_max = 100,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "quaternary_mana_recharge",
                ui_name = "Quaternary Mana Recharge Speed",
                ui_description = "Set the mana recharge speed for the quaternary wand.",
                value_default = 32.5,
                value_min = 10,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
            {
                id = "quaternary_max_mana",
                ui_name = "Quaternary Max Mana",
                ui_description = "Set the max mana for the quaternary wand.",
                value_default = 105,
                value_min = 1,
                value_max = 1000,
                scope = MOD_SETTING_SCOPE_NEW_GAME,
            },
        },
    },
}

-- Update mod settings
function ModSettingsUpdate(init_scope)
    local old_version = mod_settings_get_version(mod_id)
    mod_settings_update(mod_id, mod_settings, init_scope)
end

-- GUI Count for settings
function ModSettingsGuiCount()
    return mod_settings_gui_count(mod_id, mod_settings)
end

-- Function to draw the selected spell image
function draw_selected_spell_image(gui, spell_id, x_offset, y_offset)
    local spell_name = spell_lookup[spell_id] or "Unknown"
    local image_file = spell_images_path .. spell_name .. ".png"

    -- Set the scaling to shrink the image slightly
    local scale = 0.62  -- Adjusted value to make the image slightly smaller

    -- Check if the file exists before trying to load it
    if GuiImage(gui, 0, x_offset, y_offset, image_file, 1, scale, scale) then
        GuiImage(gui, 0, x_offset, y_offset, image_file, 1, scale, scale)
    else
        GuiText(gui, x_offset, y_offset, "Image not found: " .. spell_name)
    end
end

-- Render the GUI for settings, with custom handling for images
function ModSettingsGui(gui, in_main_menu)
    mod_settings_gui(mod_id, mod_settings, gui, in_main_menu)

    -- Start layout for Primary Spell
    GuiLayoutBeginHorizontal(gui, 0, 0, false, 2, 2)
    local primary_spell = ModSettingGet(mod_id .. ".primary_spell") or "1"
    draw_selected_spell_image(gui, primary_spell, 220, -248)  -- Position next to the text
    GuiLayoutEnd(gui)

    -- Start layout for Secondary Spell
    GuiLayoutBeginHorizontal(gui, 0, 0, false, 2, 2)
    local secondary_spell = ModSettingGet(mod_id .. ".secondary_spell") or "1"
    draw_selected_spell_image(gui, secondary_spell, 220, -240)  -- Position next to the text
    GuiLayoutEnd(gui)

    -- Start layout for Tertiary Spell
    GuiLayoutBeginHorizontal(gui, 0, 0, false, 2, 2)
    local tertiary_spell = ModSettingGet(mod_id .. ".tertiary_spell") or "1"
    draw_selected_spell_image(gui, tertiary_spell, 220, -220)  -- Position next to the text
    GuiLayoutEnd(gui)

    -- Start layout for Quaternary Spell
    GuiLayoutBeginHorizontal(gui, 0, 0, false, 2, 2)
    local quaternary_spell = ModSettingGet(mod_id .. ".quaternary_spell") or "1"
    draw_selected_spell_image(gui, quaternary_spell, 220, -200)  -- Position next to the text
    GuiLayoutEnd(gui)

    -- Print once for debugging
    if not debug_printed then
        print("Primary Spell ID: " .. primary_spell)
        print("Secondary Spell ID: " .. secondary_spell)
        print("Tertiary Spell ID: " .. tertiary_spell)
        print("Quaternary Spell ID: " .. quaternary_spell)
        debug_printed = true  -- Set flag to true after printing
    end
end

-- Initialize debug flag
debug_printed = false

-- Example spell lookup table (replace with actual mappings)
spell_lookup = {
    ["1"] = "Acid Ball",
    ["2"] = "Black Hole",
    ["3"] = "Black Hole with Death Trigger",
    ["4"] = "Bomb",
    ["5"] = "Bomb Cart",
    ["6"] = "Bubble Spark",
    ["7"] = "Bubble Spark With Trigger",
    ["8"] = "Burst Of Air",
    ["9"] = "Chain Bolt",
    ["10"] = "Chainsaw",
    ["11"] = "Cursed Sphere",
    ["12"] = "Deadly Heal",
    ["13"] = "Death Cross",
    ["14"] = "Giga Death Cross",
    ["15"] = "Plasma Beam Cross",
    ["16"] = "Digging Blast",
    ["17"] = "Digging Bolt",
    ["18"] = "Dormant Crystal",
    ["19"] = "Dormant Crystal With Trigger",
    ["20"] = "Dropper Bolt",
    ["21"] = "Dynamite",
    ["22"] = "Earthquake",
    ["23"] = "Eldritch Portal",
    ["24"] = "Energy Orb",
    ["25"] = "Energy Orb With A Trigger",
    ["26"] = "Energy Orb With A Timer",
    ["27"] = "Expanding Sphere",
    ["28"] = "Fireball",
    ["29"] = "Firebolt",
    ["30"] = "Firebolt With Trigger",
    ["31"] = "Large Firebolt",
    ["32"] = "Giant Firebolt",
    ["33"] = "Odd Firebolt",
    ["34"] = "Firebomb",
    ["35"] = "Fireworks!",
    ["36"] = "Flamethrower",
    ["37"] = "Glitter Bomb",
    ["38"] = "Glowing Lance",
    ["39"] = "Glue Ball",
    ["40"] = "Healing Bolt",
    ["41"] = "Holy Lance",
    ["42"] = "Holy Bomb",
    ["43"] = "Giga Holy Bomb",
    ["44"] = "Hookbolt",
    ["45"] = "Iceball",
    ["46"] = "Concentrated Light",
    ["47"] = "Lightning Bolt",
    ["48"] = "Thunder Charge",
    ["49"] = "Ball Lightning",
    ["50"] = "Luminous Drill",
    ["51"] = "Luminous Drill With Timer",
    ["52"] = "Magic Arrow",
    ["53"] = "Magic Arrow With Trigger",
    ["54"] = "Magic Arrow With Timer",
    ["55"] = "Magic Bolt",
    ["56"] = "Magic Bolt With Trigger",
    ["57"] = "Magic Bolt With Timer",
    ["58"] = "Magic Guard",
    ["59"] = "Big Magic Guard",
    ["60"] = "Magic Missile",
    ["61"] = "Large Magic Missile",
    ["62"] = "Giant Magic Missile",
    ["63"] = "Meteor",
    ["64"] = "Blood Mist",
    ["65"] = "Mist Of Spirits",
    ["66"] = "Slime Mist",
    ["67"] = "Toxic Mist",
    ["68"] = "Freezing Gaze",
    ["69"] = "Triplicate Bolt",
    ["70"] = "Intense Concentrated Light",
    ["71"] = "Flock Of Ducks",
    ["72"] = "Infestation",
    ["73"] = "Nuke",
    ["74"] = "Giga Nuke",
    ["75"] = "Path Of Dark Flame",
    ["76"] = "Pinpoint Of Light",
    ["77"] = "Plasma Beam",
    ["78"] = "Plasma Cutter",
    ["79"] = "Pollen",
    ["80"] = "Prickly Spore Pod",
    ["81"] = "Propane Tank",
    ["82"] = "Random Projectile Spell",
    ["83"] = "Rock",
    ["84"] = "Disc Projectile",
    ["85"] = "Giga Disc Projectile",
    ["86"] = "Summon Omega Sawblade",
    ["87"] = "Slimeball",
    ["88"] = "Spark Bolt",
    ["89"] = "Spark Bolt With Trigger",
    ["90"] = "Spark Bolt With Double Trigger",
    ["91"] = "Spark Bolt With Timer",
    ["92"] = "Bouncing Burst",
    ["93"] = "Energy Sphere",
    ["94"] = "Arrow",
    ["95"] = "Energy Sphere With Timer",
    ["96"] = "Spiral Shot",
    ["97"] = "Spitter Bolt",
    ["98"] = "Spitter Bolt With Timer",
    ["99"] = "Large Spitter Bolt",
    ["100"] = "Large Spitter Bolt With Timer",
    ["101"] = "Giant Spitter Bolt",
    ["102"] = "Giant Spitter Bolt With Timer",
    ["103"] = "Summon Deercoy",
    ["104"] = "Summon Egg",
    ["105"] = "Summon Explosive Box",
    ["106"] = "Summon Large Explosive Box",
    ["107"] = "Summon Fish",
    ["108"] = "Summon Hollow Egg",
    ["109"] = "Summon Missile",
    ["110"] = "Summon Rock Spirit",
    ["111"] = "Summon Tentacle",
    ["112"] = "Summon Tentacle With Timer",
    ["113"] = "Swapper",
    ["114"] = "Homebringer Teleport Bolt",
    ["115"] = "Teleport Bolt",
    ["116"] = "Return",
    ["117"] = "Small Teleport Bolt",
    ["118"] = "Unstable Crystal",
    ["119"] = "Unstable Crystal With Trigger",
    ["120"] = "White Hole",
    ["121"] = "Worm Launcher",
    ["122"] = "Horizontal Barrier",
    ["123"] = "Vertical Barrier",
    ["124"] = "Square Barrier",
    ["125"] = "Circle of Unstable Metamorphosis",
    ["126"] = "Circle of Shielding",
    ["127"] = "Circle of Transmogrification",
    ["128"] = "Circle of Buoyancy",
    ["129"] = "Circle of Fervour",
    ["130"] = "Circle of Displacement",
    ["131"] = "Circle of Stillness",
    ["132"] = "Circle of Thunder",
    ["133"] = "Circle of Vigour",
    ["134"] = "Rain Cloud",
    ["135"] = "Oil Cloud",
    ["136"] = "Blood Cloud",
    ["137"] = "Acid Cloud",
    ["138"] = "Thundercloud",
    ["139"] = "Destruction",
    ["140"] = "Explosive Detonator",
    ["141"] = "Glittering Field",
    ["142"] = "Matosade",
    ["143"] = "Meteorisade",
    ["144"] = "Summon Fly Swarm",
    ["145"] = "Summon Firebug Swarm",
    ["146"] = "Summon Wasp Swarm",
    ["147"] = "Delayed Spellcast",
    ["148"] = "Muodonmuutos",
    ["149"] = "Projectile Transmutation Field",
    ["150"] = "Projectile Thunder Field",
    ["151"] = "Projectile Gravity Field",
    ["152"] = "Random Static Projectile Spell",
    ["153"] = "Omega Black Hole",
    ["154"] = "Giga White Hole",
    ["155"] = "Giga Black Hole",
    ["156"] = "Explosion",
    ["157"] = "Explosion of Brimstone",
    ["158"] = "Explosion of Poison",
    ["159"] = "Explosion of Spirits",
    ["160"] = "Explosion of Thunder",
    ["161"] = "Magical Explosion",
    ["162"] = "Omega White Hole",
    ["163"] = "Summon Friendly Fly",
    ["164"] = "Powder Vacuum Field",
    ["165"] = "Vacuum Field",
    ["166"] = "Liquid Vacuum Field"
}

-- Path where images are stored
spell_images_path = "mods/Custom Start/data/items_gfx/Spell Images/"
